// <auto-generated />
namespace Sapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VendaSapato201909292107 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VendaSapato201909292107));
        
        string IMigrationMetadata.Id
        {
            get { return "201909300007436_VendaSapato201909292107"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
