// <auto-generated />
namespace Sapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class corrigindo_endereco_201909162100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corrigindo_endereco_201909162100));
        
        string IMigrationMetadata.Id
        {
            get { return "201909170001475_corrigindo_endereco_201909162100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
