// <auto-generated />
namespace Sapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class corrigido_mais_uma_entidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corrigido_mais_uma_entidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201909170022217_corrigido_mais_uma_entidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
