// <auto-generated />
namespace Sapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modelo_sapatos_201909301915 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelo_sapatos_201909301915));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302215468_modelo_sapatos_201909301915"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
