// <auto-generated />
namespace Sapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class venda_sapato201909301958 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(venda_sapato201909301958));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302258479_venda_sapato201909301958"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
